"""Regression test for the portal-side vault-migrate fixture (Brick 6b).

The portal's TS deed-migrate co-spend builder
(``vault-migrate-spend.service.ts``) is validated against a JSON fixture +
a ``p2_vault`` hex module generated by
``scripts/dump_vault_migrate_fixtures.py``.  This test re-runs the generator
and asserts the on-disk files match, so any change to ``vault_driver.py`` /
``p2_vault.clsp`` / ``vault_singleton_inner.clsp`` that affects the TS port
surfaces here as a diff.  The fixture IS the cross-repo contract.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import pytest

_REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(_REPO_ROOT / "scripts"))

import dump_vault_migrate_fixtures  # noqa: E402


def test_fixture_matches_committed_file() -> None:
    expected = dump_vault_migrate_fixtures.build_fixture()
    fixture_path = dump_vault_migrate_fixtures.fixture_destination()
    if not fixture_path.exists():
        pytest.fail(
            f"Portal fixture file is missing at {fixture_path}.\n"
            "Run `scripts/dump_vault_migrate_fixtures.py` to regenerate it."
        )
    on_disk = json.loads(fixture_path.read_text())
    assert on_disk == expected, (
        "Portal vault-migrate fixture is out of sync with the Python helpers.\n"
        "Run `python scripts/dump_vault_migrate_fixtures.py` and commit the diff."
    )


def test_p2_vault_hex_module_matches_committed_file() -> None:
    expected = dump_vault_migrate_fixtures.build_puzzle_hex_module()
    hex_path = dump_vault_migrate_fixtures.puzzle_hex_destination()
    if not hex_path.exists():
        pytest.fail(
            f"Portal p2_vault hex module is missing at {hex_path}.\n"
            "Run `scripts/dump_vault_migrate_fixtures.py` to regenerate it."
        )
    assert hex_path.read_text() == expected, (
        "Portal p2-vault-current.puzzle-hex.ts is out of sync with P2_VAULT_MOD.\n"
        "Run `python scripts/dump_vault_migrate_fixtures.py` and commit the diff."
    )


def test_spend_migrate_opcode_is_pinned() -> None:
    """SPEND_MIGRATE = b'm' = 0x6d.  Pins the opcode the signing tree binds."""
    fixture = dump_vault_migrate_fixtures.build_fixture()
    assert fixture["constants"]["spend_migrate"] == 0x6D


def test_fixture_covers_all_helpers() -> None:
    fixture = dump_vault_migrate_fixtures.build_fixture()
    assert fixture["constants"], "constants section must be non-empty"
    assert fixture["migrate_signing_tree"], "migrate_signing_tree cases must be non-empty"
    assert fixture["new_p2_vault_puzzle_hash"], "new_p2_vault_puzzle_hash cases must be non-empty"
    assert fixture["vault_migrate_spend"], "vault_migrate_spend cases must be non-empty"
    assert fixture["deed_migrate_spend"], "deed_migrate_spend cases must be non-empty"
